BEGIN;

UPDATE public.equipment_items
SET data = jsonb_set(
  data,
  '{description}',
  to_jsonb(COALESCE(data->>'description', '') || ' Não é possível sintonizar-se com um robe cuja tendência não corresponda à sua. Enquanto o veste sem armadura, sua CA base é 15 + modificador de Destreza; você tem vantagem em testes de resistência contra magias e outros efeitos mágicos, e sua CD de resistência de magia e seus ataques com magia recebem +2.')
)
WHERE id = 'robe-do-arquimago';

INSERT INTO public.equipment_items (id, name, category, subcategory, data)
SELECT id, name, 'magic', subcategory,
  jsonb_build_object(
    'id', id,
    'name', name,
    'category', 'magic',
    'subcategory', subcategory,
    'rarity', rarity,
    'attunement', attunement,
    'priceCp', NULL,
    'weightKg', NULL,
    'unit', 'unidade',
    'description', description,
    'properties', ARRAY[]::text[],
    'sourcePage', NULL,
    'aliases', ARRAY[]::text[]
  )
FROM (VALUES
  ('robe-dos-itens-uteis', 'Robe dos Itens Úteis', 'Robes', 'incomum', NULL, 'Remendos arrancados com uma ação tornam-se os objetos ou criaturas representados; após o último, o robe vira roupa comum. Traz dois de cada: adaga, lanterna furta-fogo cheia e acesa, espelho de aço, vara de 3 m, corda de cânhamo de 15 m e saco. Também possui 4d4 remendos adicionais, determinados pelo Mestre: sacola com 100 po; caixa de prata valendo 500 po; porta de ferro barrada; 10 gemas de 100 po cada; escada de 7 m; cavalo com alforjes; fosso cúbico de 3 m; quatro poções de cura; barco a remo; pergaminho com magia de 1º a 3º nível; dois mastins; janela; ou aríete portátil.'),
  ('robe-dos-olhos', 'Robe dos Olhos', 'Robes', 'raro', 'sim', 'Permite ver em todas as direções e concede vantagem em testes de Sabedoria (Percepção) ligados à visão, visão no escuro a 36 m e visão de criaturas e objetos invisíveis e do Plano Etéreo nesse alcance. Os olhos do robe nunca se fecham nem desviam; fechar os próprios olhos não suprime o efeito. Luz conjurada no robe ou luz do dia a até 1,5 m cega o usuário por 1 minuto; no fim de cada turno, teste de Constituição CD 11 ou 15, respectivamente, encerra a cegueira.'),
  ('sacola-prestativa-de-heward', 'Sacola Prestativa de Heward', 'Bolsas', 'raro', NULL, 'Duas bolsas laterais extradimensionais comportam até 10 kg e 60 litros cada; a bolsa central comporta até 2 m³ ou 40 kg. Sempre pesa 2,5 kg. Guardar itens segue a interação normal; recuperar exige uma ação e o item procurado surge no topo. Sobrecarga, perfuração ou rasgo destrói a sacola e perde o conteúdo, exceto artefatos, que reaparecem em algum lugar. Virada do avesso, expele o conteúdo ileso e precisa ser desvirada para funcionar. Criatura que respire sobrevive dentro por até 10 minutos, depois sufoca. Inserida em mochila de carga, buraco portátil ou espaço extradimensional similar, ambos são destruídos e abre-se portal unidirecional ao Plano Astral, sugando criaturas a até 3 m para local aleatório.'),
  ('saco-de-feijoes', 'Saco de Feijões', 'Bolsas', 'raro', NULL, 'Contém 3d4 feijões e pesa 250 g mais 125 g por feijão. Despejá-los no solo causa explosão de fogo em raio de 3 m (Destreza CD 15; 5d4 de dano, metade se passar) e incendeia objetos inflamáveis não vestidos ou carregados. Plantar e regar um feijão produz após 1 minuto um efeito determinado pelo Mestre ou por d100: cogumelos com efeitos benéficos ou venenosos; gêiser; ente; estátua animada; fogueira azul; guinchadores; sapos que se transformam em monstros; bulette; árvore com poções e veneno; ovos que podem aumentar permanentemente um atributo ou causar dano de energia; pirâmide com senhor das múmias e tesouro; ou pé de feijão gigante cujo topo leva a destino escolhido pelo Mestre.'),
  ('sandalias-de-patas-de-aranha', 'Sandálias de Patas de Aranha', 'Calçados', 'incomum', 'sim', 'Concedem deslocamento de escalada igual ao de caminhada e permitem atravessar paredes e tetos de cabeça para baixo, mantendo as mãos livres. Não funcionam assim em superfícies escorregadias, como gelo ou óleo.'),
  ('sela-do-cavaleiro', 'Sela do Cavaleiro', 'Selas', 'incomum', NULL, 'Enquanto consciente e montado nesta sela, você não pode ser desmontado contra a vontade; ataques contra sua montaria têm desvantagem.'),
  ('solvente-universal', 'Solvente Universal', 'Itens maravilhosos', 'lendário', NULL, 'Com uma ação, dissolve instantaneamente até 30 cm² de cola tocada, inclusive Cola Soberana.'),
  ('talisma-da-bondade-pura', 'Talismã da Bondade Pura', 'Talismãs', 'lendário', 'criatura de tendência benigna', 'Criatura neutra no eixo bem/mal sofre 6d6 de dano radiante ao tocar; criatura má sofre 8d6. O dano repete-se ao fim de cada turno em que segure ou carregue o talismã. Clérigo ou paladino bom pode usá-lo como símbolo sagrado e recebe +2 em ataques com magia enquanto o usa ou empunha. Tem 7 cargas; com ação e 1 carga, escolhe criatura má no chão a até 36 m: Destreza CD 20; se falhar, cai numa fissura, é destruída sem restos e a fissura se fecha. Ao gastar a última carga, o talismã é destruído em fagulhas douradas.'),
  ('talisma-da-esfera', 'Talismã da Esfera', 'Talismãs', 'lendário', 'sim', 'Enquanto segura o talismã, adiciona o bônus de proficiência ao teste de Inteligência (Arcanismo) para controlar uma Esfera da Aniquilação. Se começar o turno controlando uma esfera, pode usar uma ação para movê-la até 3 m + 3 vezes seu modificador de Inteligência.'),
  ('talisma-do-mal-absoluto', 'Talismã do Mal Absoluto', 'Talismãs', 'lendário', 'criatura de tendência maligna', 'Criatura neutra no eixo bem/mal sofre 6d6 de dano necrótico ao tocar; criatura boa sofre 8d6. O dano repete-se ao fim de cada turno em que segure ou carregue o talismã. Clérigo ou paladino maligno pode usá-lo como símbolo sagrado e recebe +2 em ataques com magia enquanto o usa ou empunha. Tem 6 cargas; com ação e 1 carga, escolhe criatura boa no chão a até 36 m: Destreza CD 20; se falhar, cai numa fissura e é destruída sem restos. Ao gastar a última carga, o talismã se dissolve em lodo e é destruído.'),
  ('tapete-voador', 'Tapete Voador', 'Itens maravilhosos', 'muito raro', NULL, 'Com ação e palavra de comando, flutua e voa na direção falada enquanto você estiver a até 9 m. Variante determinada por d100: 01–20, 1 × 1,5 m, capacidade 100 kg, voo 21 m; 21–55, 1,2 × 1,8 m, 200 kg, voo 18 m; 56–80, 1,5 × 2 m, 300 kg, voo 12 m; 81–100, 1,8 × 2,8 m, 400 kg, voo 9 m. Carrega até o dobro da capacidade, mas acima do limite normal seu deslocamento cai à metade.'),
  ('tiara-do-intelecto', 'Tiara do Intelecto', 'Tiaras', 'incomum', 'sim', 'Define Inteligência como 19 enquanto usada; não tem efeito se o valor já for 19 ou maior.'),
  ('tomo-da-compreensao', 'Tomo da Compreensão', 'Livros', 'muito raro', NULL, 'Estudar e praticar por 48 horas em até 6 dias aumenta Sabedoria em 2, até o máximo permitido. Depois, o tomo perde a magia e a recupera após um século.'),
  ('tomo-da-lingua-quieta', 'Tomo da Língua Quieta', 'Livros', 'lendário', 'mago', 'Existem cinco tomos, cada um com uma língua dissecada na capa, primeiras páginas indecifráveis e restantes em branco. Pode servir como grimório e foco arcano. Enquanto o segura, uma ação bônus conjura uma magia escrita nele sem gastar espaço de magia nem componentes verbais ou somáticos; reutiliza após o amanhecer. Remover a língua enquanto sintonizado apaga permanentemente todas as magias. Vecna observa o usuário e pode escrever mensagens ocultas, que surgem à meia-noite e desaparecem depois de lidas.'),
  ('tomo-de-lideranca-e-influencia', 'Tomo de Liderança e Influência', 'Livros', 'muito raro', NULL, 'Estudar e praticar por 48 horas em até 6 dias aumenta Carisma em 2, até o máximo permitido. Recupera a magia após um século.'),
  ('tomo-dos-grandes-pensamentos', 'Tomo dos Grandes Pensamentos', 'Livros', 'muito raro', NULL, 'Estudar e praticar por 48 horas em até 6 dias aumenta Inteligência em 2, até o máximo permitido. Recupera a magia após um século.'),
  ('tridente-de-comandar-peixes', 'Tridente de Comandar Peixes', 'Armas mágicas', 'incomum', 'sim', 'Arma mágica com 3 cargas. Com uma ação e 1 carga, conjura dominar besta (CD 15) em uma besta com deslocamento de natação inato. Recupera 1d3 cargas ao amanhecer.'),
  ('trombeta-da-destruicao', 'Trombeta da Destruição', 'Instrumentos', 'raro', NULL, 'Com uma ação, palavra de comando e sopro, cria cone de 9 m audível a 180 m. Criaturas fazem Constituição CD 15 ou sofrem 5d6 de dano trovejante e ficam surdas por 1 minuto; metade do dano e sem surdez se passarem. Vidro e cristal têm desvantagem e sofrem 10d6. Cada uso tem 20% de chance de a trombeta explodir, causando 10d6 de dano de fogo ao usuário e destruindo o item.'),
  ('trombeta-do-valhalla', 'Trombeta do Valhalla', 'Instrumentos', 'variável', NULL, 'Com uma ação, invoca furiosos espirituais a até 18 m; permanecem por 1 hora ou até chegarem a 0 PV e a trombeta só pode ser usada novamente após 7 dias. Variantes: prata (rara), 2d4+2 furiosos, sem requisito; latão (rara), 3d4+3, proficiência com todas as armas simples; bronze (muito raro), 4d4+4, proficiência com todas as armaduras médias; ferro (lendária), 5d4+5, proficiência com todas as armas marciais. Sem o requisito, os furiosos atacam o usuário; caso contrário, são amistosos e obedecem.'),
  ('unguento-de-keoghtom', 'Unguento de Keoghtom', 'Unguentos', 'incomum', NULL, 'Jarro com 1d4+1 doses; pesa 250 g. Com uma ação, ingerir ou aplicar uma dose recupera 2d8+2 PV e cura envenenamento e qualquer doença.'),
  ('varinha-das-maravilhas', 'Varinha das Maravilhas', 'Varinhas', 'rara', 'conjurador', 'Tem 7 cargas. Com uma ação e 1 carga, escolhe criatura, objeto ou ponto a até 36 m e determina o efeito por d100: lentidão; fogo das fadas; usuário atordoado; lufada de vento; detectar pensamentos ou dano psíquico ao usuário; névoa fétida; chuva; animal que aparece próximo; relâmpago; borboletas que criam escuridão densa; aumentar o alvo; escuridão; crescimento de grama; objeto enviado ao Plano Etéreo; usuário reduzido; bola de fogo; invisibilidade; folhas; gemas que causam dano; luzes que podem cegar; pele azulada; ou possível petrificação. Magias têm CD 15 e alcance de 36 m quando aplicável. Recupera 1d6+1 cargas ao amanhecer; ao gastar a última, uma rolagem de 1 em d20 a transforma em cinzas. Os valores das gemas geradas não são preço da varinha.'),
  ('varinha-de-bolas-de-fogo', 'Varinha de Bolas de Fogo', 'Varinhas', 'rara', 'conjurador', 'Tem 7 cargas. Com uma ação, conjura bola de fogo (CD 15), 3º nível por 1 carga e +1 nível por carga adicional. Recupera 1d6+1 cargas ao amanhecer; ao gastar a última, uma rolagem de 1 em d20 destrói a varinha.'),
  ('varinha-de-deteccao-de-inimigos', 'Varinha de Detecção de Inimigos', 'Varinhas', 'rara', 'sim', 'Tem 7 cargas. Com uma ação, palavra de comando e 1 carga, por 1 minuto informa a direção, mas não a distância, da criatura hostil mais próxima em 18 m, inclusive se etérea, invisível, disfarçada ou escondida. O efeito termina ao soltar a varinha. Recupera 1d6+1 cargas ao amanhecer; ao gastar a última, uma rolagem de 1 em d20 a destrói.'),
  ('varinha-de-detectar-magia', 'Varinha de Detectar Magia', 'Varinhas', 'incomum', NULL, 'Tem 3 cargas. Com uma ação e 1 carga, conjura detectar magia. Recupera 1d3 cargas ao amanhecer.'),
  ('varinha-de-medo', 'Varinha de Medo', 'Varinhas', 'rara', 'sim', 'Tem 7 cargas; recupera 1d6+1 ao amanhecer e pode ser destruída ao gastar a última carga (1 em d20). Comando: ação e 1 carga para conjurar comando (CD 15). Cone de Medo: ação e 2 cargas criam cone de 18 m; Sabedoria CD 15 ou a criatura fica amedrontada por 1 minuto, deve se afastar, não pode se aproximar voluntariamente a menos de 9 m nem usar reações, e repete o teste ao fim de cada turno.'),
  ('varinha-de-metamorfose', 'Varinha de Metamorfose', 'Varinhas', 'muito raro', 'conjurador', 'Tem 7 cargas. Com uma ação e 1 carga, conjura metamorfose (CD 15). Recupera 1d6+1 cargas ao amanhecer; ao gastar a última, uma rolagem de 1 em d20 a destrói.'),
  ('varinha-de-misseis-magicos', 'Varinha de Mísseis Mágicos', 'Varinhas', 'incomum', NULL, 'Tem 7 cargas. Com uma ação, conjura mísseis mágicos de 1º nível por 1 carga, +1 nível por carga adicional. Recupera 1d6+1 cargas ao amanhecer; ao gastar a última, uma rolagem de 1 em d20 a destrói.'),
  ('varinha-de-obrigacao', 'Varinha de Obrigação', 'Varinhas', 'rara', 'conjurador', 'Tem 7 cargas; recupera 1d6+1 ao amanhecer e pode ser destruída ao gastar a última carga (1 em d20). Com ação, conjura imobilizar monstro (5 cargas) ou imobilizar pessoa (2), CD 17. Uma reação e 1 carga concedem vantagem em resistência contra paralisia ou impedimento, ou em teste para escapar de agarrão.'),
  ('varinha-de-paralisia', 'Varinha de Paralisia', 'Varinhas', 'rara', 'conjurador', 'Tem 7 cargas. Com uma ação e 1 carga, faz ataque à distância com bônus de ataque mágico contra criatura visível a até 18 m; ao acertar, paralisa por 1 minuto. O alvo repete o teste de resistência ao fim de cada turno, mas o documento não especifica atributo nem CD. Recupera 1d6+1 cargas ao amanhecer; ao gastar a última, uma rolagem de 1 em d20 a destrói.'),
  ('varinha-de-relampagos', 'Varinha de Relâmpagos', 'Varinhas', 'rara', 'conjurador', 'Tem 7 cargas. Com uma ação, conjura relâmpago (CD 15), 3º nível por 1 carga e +1 nível por carga adicional. Recupera 1d6+1 cargas ao amanhecer; ao gastar a última, uma rolagem de 1 em d20 a destrói.'),
  ('varinha-de-segredos', 'Varinha de Segredos', 'Varinhas', 'incomum', NULL, 'Tem 3 cargas. Com uma ação e 1 carga, se houver porta secreta ou armadilha a até 9 m, pulsa e aponta para a mais próxima. Recupera 1d3 cargas ao amanhecer.'),
  ('varinha-de-teia', 'Varinha de Teia', 'Varinhas', 'incomum', 'conjurador', 'Tem 7 cargas. Com uma ação e 1 carga, conjura teia (CD 15). Recupera 1d6+1 cargas ao amanhecer; ao gastar a última, uma rolagem de 1 em d20 a destrói.'),
  ('varinha-do-arcano-de-guerra', 'Varinha do Arcano de Guerra', 'Varinhas', 'variável', 'conjurador', 'Concede o bônus indicado nas jogadas de ataque com magia e permite ignorar meia-cobertura nesses ataques. Variantes: +1 (incomum), +2 (rara) e +3 (muito rara).'),
  ('vassoura-voadora', 'Vassoura Voadora', 'Itens maravilhosos', 'incomum', NULL, 'Pesa 1,5 kg. Ao montá-la e dizer a palavra de comando, voa a 15 m; carrega até 200 kg, mas acima de 100 kg voa a 9 m. Ao aterrissar, para de flutuar. Pode viajar sozinha a um destino familiar a até 1,5 km, mediante palavra de comando e nome do local, e retornar com nova palavra se ainda estiver nesse alcance.'),
  ('vela-de-invocacao', 'Vela de Invocação', 'Velas', 'muito raro', 'sim', 'Dedicada a uma divindade e de tendência correspondente, detectável por detectar mal e bem. A tendência pode ser determinada por tabela d20. Acender requer ação; dura 4 horas no total e pode ser apagada e reutilizada, contando o consumo em minutos. Acesa, emite penumbra a 9 m; criaturas de tendência correspondente têm vantagem em ataques, resistências e testes de habilidade. Clérigo ou druida de tendência correspondente pode conjurar magias preparadas de 1º nível sem gastar espaços, mantendo o efeito nesse nível. Na primeira vez que for acesa, pode conjurar portal, destruindo a vela.'),
  ('vingadora-sagrada', 'Vingadora Sagrada', 'Armas mágicas', 'lendário', 'paladino', 'Espada mágica +3 nas jogadas de ataque e dano. Ao atingir corruptor ou morto-vivo, causa 2d10 de dano radiante adicional. Enquanto empunhada, cria aura de 3 m que concede ao usuário e criaturas amigáveis vantagem em testes de resistência contra magias e outros efeitos mágicos; para paladino de nível 17 ou superior, o raio é 9 m.')
) AS items(id, name, subcategory, rarity, attunement, description)
ON CONFLICT (id) DO NOTHING;

COMMIT;
