BEGIN;

INSERT INTO public.backgrounds (slug, name, source_page)
VALUES ('assombrado', 'Assombrado', 209)
ON CONFLICT (slug) DO UPDATE
SET name = excluded.name,
    source_page = excluded.source_page;

INSERT INTO public.equipment_items (id, name, category, subcategory, data) VALUES
('estaca-de-madeira', 'Estaca de madeira', 'gear', 'Ferramentas e utilidades', '{"id":"estaca-de-madeira","name":"Estaca de madeira","category":"gear","subcategory":"Ferramentas e utilidades","priceCp":5,"weightKg":0.5,"unit":"unidade","description":"Estaca simples de madeira usada para prender criaturas ou objetos.","properties":[],"sourcePage":209,"aliases":[]}'::jsonb),
('simbolo-sagrado', 'Símbolo sagrado', 'gear', 'Símbolo sagrado', '{"id":"simbolo-sagrado","name":"Símbolo sagrado","category":"gear","subcategory":"Símbolo sagrado","priceCp":500,"weightKg":0.5,"unit":"unidade","description":"Símbolo de uma divindade, usado como foco sagrado.","properties":[],"sourcePage":209,"aliases":[]}'::jsonb),
('haunted-trinket-01', 'Bugiganga assombrada (01)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-01","name":"Bugiganga assombrada (01)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma imagem que você desenhou quando criança do seu amigo imaginário.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-02', 'Bugiganga assombrada (02)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-02","name":"Bugiganga assombrada (02)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma fechadura que se abre quando sangue pinga no buraco da chave.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-03', 'Bugiganga assombrada (03)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-03","name":"Bugiganga assombrada (03)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Roupas roubadas de um espantalho.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-04', 'Bugiganga assombrada (04)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-04","name":"Bugiganga assombrada (04)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um pião esculpido com quatro rostos: feliz, triste, furioso e morto.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-05', 'Bugiganga assombrada (05)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-05","name":"Bugiganga assombrada (05)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"O colar de um irmão que morreu no dia em que você nasceu.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-06', 'Bugiganga assombrada (06)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-06","name":"Bugiganga assombrada (06)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma peruca de alguém executado por decapitação.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-07', 'Bugiganga assombrada (07)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-07","name":"Bugiganga assombrada (07)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma carta nunca aberta, escrita para você por seu pai moribundo.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-08', 'Bugiganga assombrada (08)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-08","name":"Bugiganga assombrada (08)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um relógio de bolso que anda para trás por uma hora à meia-noite.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-09', 'Bugiganga assombrada (09)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-09","name":"Bugiganga assombrada (09)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um casaco de inverno roubado de um soldado moribundo.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-10', 'Bugiganga assombrada (10)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-10","name":"Bugiganga assombrada (10)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um frasco de tinta invisível que só pode ser lida ao pôr do sol.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-11', 'Bugiganga assombrada (11)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-11","name":"Bugiganga assombrada (11)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um cantil que se enche quando enterrado com um morto por uma noite.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-12', 'Bugiganga assombrada (12)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-12","name":"Bugiganga assombrada (12)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um conjunto de talheres usado por um rei em sua última refeição.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-13', 'Bugiganga assombrada (13)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-13","name":"Bugiganga assombrada (13)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma luneta que sempre mostra o mundo sob uma tempestade terrível.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-14', 'Bugiganga assombrada (14)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-14","name":"Bugiganga assombrada (14)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um camafeu com o rosto do retrato arranhado.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-15', 'Bugiganga assombrada (15)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-15","name":"Bugiganga assombrada (15)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma lanterna com uma vela preta que nunca acaba e queima com chama verde.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-16', 'Bugiganga assombrada (16)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-16","name":"Bugiganga assombrada (16)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma xícara de chá de um conjunto infantil, manchada de sangue.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-17', 'Bugiganga assombrada (17)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-17","name":"Bugiganga assombrada (17)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um pequeno livro preto que registra apenas os seus sonhos quando você dorme.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-18', 'Bugiganga assombrada (18)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-18","name":"Bugiganga assombrada (18)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um colar formado por símbolos sagrados entrelaçados de uma dúzia de divindades.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-19', 'Bugiganga assombrada (19)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-19","name":"Bugiganga assombrada (19)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um laço que parece mais pesado do que deveria.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-20', 'Bugiganga assombrada (20)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-20","name":"Bugiganga assombrada (20)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma gaiola para a qual pequenos pássaros voam, mas da qual nunca comem nem saem.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-21', 'Bugiganga assombrada (21)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-21","name":"Bugiganga assombrada (21)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma caixa de lepidopterista cheia de mariposas mortas com padrões de caveira nas asas.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-22', 'Bugiganga assombrada (22)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-22","name":"Bugiganga assombrada (22)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma jarra de línguas de carniçais em conserva.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-23', 'Bugiganga assombrada (23)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-23","name":"Bugiganga assombrada (23)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"A mão de madeira de um pirata notório.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-24', 'Bugiganga assombrada (24)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-24","name":"Bugiganga assombrada (24)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma urna com as cinzas de um parente morto.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-25', 'Bugiganga assombrada (25)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-25","name":"Bugiganga assombrada (25)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um espelho de mão com um relevo de bronze de uma medusa no verso.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-26', 'Bugiganga assombrada (26)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-26","name":"Bugiganga assombrada (26)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Luvas de couro pálido feitas com unhas de marfim.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-27', 'Bugiganga assombrada (27)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-27","name":"Bugiganga assombrada (27)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Dados feitos dos nós dos dedos de um charlatão notório.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-28', 'Bugiganga assombrada (28)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-28","name":"Bugiganga assombrada (28)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um anel de chaves para fechaduras esquecidas.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-29', 'Bugiganga assombrada (29)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-29","name":"Bugiganga assombrada (29)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Pregos do caixão de um assassino.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-30', 'Bugiganga assombrada (30)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-30","name":"Bugiganga assombrada (30)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma chave da cripta da família.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-31', 'Bugiganga assombrada (31)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-31","name":"Bugiganga assombrada (31)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um buquê de flores funerárias que sempre parece e cheira fresco.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-32', 'Bugiganga assombrada (32)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-32","name":"Bugiganga assombrada (32)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma vara usada para disciplinar você quando criança.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-34', 'Bugiganga assombrada (34)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-34","name":"Bugiganga assombrada (34)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma bengala com ponteira de ferro que produz faíscas ao bater em pedra.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-35', 'Bugiganga assombrada (35)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-35","name":"Bugiganga assombrada (35)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma bandeira de um navio perdido no mar.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-36', 'Bugiganga assombrada (36)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-36","name":"Bugiganga assombrada (36)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"A cabeça de uma boneca de porcelana que parece sempre olhar para você.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-37', 'Bugiganga assombrada (37)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-37","name":"Bugiganga assombrada (37)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma cabeça de lobo de prata que também é um apito.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-38', 'Bugiganga assombrada (38)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-38","name":"Bugiganga assombrada (38)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um pequeno espelho que mostra uma versão muito mais velha de quem olha.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-39', 'Bugiganga assombrada (39)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-39","name":"Bugiganga assombrada (39)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um pequeno e gasto livro de cantigas infantis.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-40', 'Bugiganga assombrada (40)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-40","name":"Bugiganga assombrada (40)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma garra mumificada de corvo.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-41', 'Bugiganga assombrada (41)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-41","name":"Bugiganga assombrada (41)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um pingente quebrado de dragão de prata, sempre frio ao toque.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-42', 'Bugiganga assombrada (42)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-42","name":"Bugiganga assombrada (42)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma pequena caixa trancada que cantarola uma melodia à noite, mas que você sempre esquece pela manhã.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-43', 'Bugiganga assombrada (43)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-43","name":"Bugiganga assombrada (43)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um tinteiro que deixa quem olha para ele um pouco nauseado.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-44', 'Bugiganga assombrada (44)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-44","name":"Bugiganga assombrada (44)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma boneca antiga de madeira escura e densa, sem uma mão e um pé.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-45', 'Bugiganga assombrada (45)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-45","name":"Bugiganga assombrada (45)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um capuz negro de carrasco.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-46', 'Bugiganga assombrada (46)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-46","name":"Bugiganga assombrada (46)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma bolsa feita de carne, com cordão de tendão.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-47', 'Bugiganga assombrada (47)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-47","name":"Bugiganga assombrada (47)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um pequeno carretel de linha preta que nunca acaba.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-48', 'Bugiganga assombrada (48)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-48","name":"Bugiganga assombrada (48)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma pequena estatueta mecânica de bailarina, sem uma engrenagem e que não funciona.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-49', 'Bugiganga assombrada (49)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-49","name":"Bugiganga assombrada (49)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um cachimbo de madeira negra que cria baforadas de fumaça em forma de caveira.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-50', 'Bugiganga assombrada (50)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-50","name":"Bugiganga assombrada (50)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um frasco de perfume cujo aroma só certas criaturas podem detectar.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-51', 'Bugiganga assombrada (51)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-51","name":"Bugiganga assombrada (51)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma pedra que emite um único suspiro interminável.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-52', 'Bugiganga assombrada (52)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-52","name":"Bugiganga assombrada (52)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma boneca de pano com dois pontos vermelhos no pescoço.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-54', 'Bugiganga assombrada (54)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-54","name":"Bugiganga assombrada (54)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um pote de conserva com uma gosma animada inofensiva, mas agitada.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-55', 'Bugiganga assombrada (55)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-55","name":"Bugiganga assombrada (55)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um dado de madeira preta com o número 1 em todas as faces.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-56', 'Bugiganga assombrada (56)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-56","name":"Bugiganga assombrada (56)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um retrato infantil com “nascido” escrito no verso, junto com a data do próximo ano.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-57', 'Bugiganga assombrada (57)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-57","name":"Bugiganga assombrada (57)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um dente de tubarão do tamanho de uma adaga.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-58', 'Bugiganga assombrada (58)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-58","name":"Bugiganga assombrada (58)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um dedo que criou raízes em um pequeno vaso.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-59', 'Bugiganga assombrada (59)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-59","name":"Bugiganga assombrada (59)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma caixa de ferramentas com os restos de um aracnídeo mecânico perigoso, mas quebrado.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-60', 'Bugiganga assombrada (60)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-60","name":"Bugiganga assombrada (60)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma concha de caracol iridescente do tamanho de uma jarra que às vezes estremece ou tomba sem explicação.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-61', 'Bugiganga assombrada (61)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-61","name":"Bugiganga assombrada (61)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"O diário de bordo de um navio quebra-gelo chamado Haifisch.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-62', 'Bugiganga assombrada (62)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-62","name":"Bugiganga assombrada (62)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um pequeno retrato seu quando criança, ao lado do seu gêmeo vestido de modo idêntico.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-63', 'Bugiganga assombrada (63)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-63","name":"Bugiganga assombrada (63)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um relógio de bolso prateado com treze horas no mostrador.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-64', 'Bugiganga assombrada (64)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-64","name":"Bugiganga assombrada (64)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Um entalhe em madeira de um lobo devorando a própria perna traseira.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-65', 'Bugiganga assombrada (65)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-65","name":"Bugiganga assombrada (65)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma prancheta gravada com caveiras de corvos.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb),
('haunted-trinket-66', 'Bugiganga assombrada (66)', 'gear', 'Bugiganga assombrada', '{"id":"haunted-trinket-66","name":"Bugiganga assombrada (66)","category":"gear","subcategory":"Bugiganga assombrada","priceCp":null,"weightKg":null,"unit":"unidade","description":"Uma estatueta úmida de coral de uma lampreia com braços, pernas e postura bípede.","properties":[],"sourcePage":220,"aliases":[]}'::jsonb)
ON CONFLICT (id) DO UPDATE
SET name = excluded.name,
    category = excluded.category,
    subcategory = excluded.subcategory,
    data = excluded.data;

UPDATE public.equipment_items
SET data = jsonb_set(data, '{description}', '"Uma caixa de música que toca sozinha sempre que alguém que a segura dança."'::jsonb)
WHERE id = 'caixa-de-musica';

UPDATE public.equipment_items
SET data = jsonb_set(data, '{description}', '"Um brinquedo de mola com a manivela faltando."'::jsonb)
WHERE id = 'brinquedo-mecanico';

INSERT INTO public.equipment_packs (id, name, price_cp, source_page)
VALUES ('monster-hunter', 'Pacote de Caçador de Monstro', 4578, 209)
ON CONFLICT (id) DO UPDATE
SET name = excluded.name,
    price_cp = excluded.price_cp,
    source_page = excluded.source_page;

INSERT INTO public.equipment_pack_items (pack_id, item_id, quantity) VALUES
('monster-hunter', 'bau', 1),
('monster-hunter', 'pe-de-cabra', 1),
('monster-hunter', 'martelo', 1),
('monster-hunter', 'estaca-de-madeira', 3),
('monster-hunter', 'simbolo-sagrado', 1),
('monster-hunter', 'agua-benta-frasco', 1),
('monster-hunter', 'algemas', 1),
('monster-hunter', 'espelho-de-aco', 1),
('monster-hunter', 'oleo-frasco', 1),
('monster-hunter', 'caixa-de-fogo', 1),
('monster-hunter', 'tocha', 3)
ON CONFLICT (pack_id, item_id) DO UPDATE SET quantity = excluded.quantity;

COMMIT;
