BEGIN;

INSERT INTO public.equipment_items (id, name, category, subcategory, data)
SELECT id, name, 'magic', subcategory,
  jsonb_build_object(
    'id', id,
    'name', name,
    'category', 'magic',
    'subcategory', subcategory,
    'rarity', rarity,
    'attunement', attunement,
    'priceCp', price_cp,
    'weightKg', NULL,
    'unit', 'unidade',
    'description', description,
    'properties', ARRAY[]::text[],
    'sourcePage', NULL,
    'aliases', ARRAY[]::text[]
  )
FROM (VALUES
  ('capa-do-saltimbanco', 'Capa do Saltimbanco', 'Capas', 'raro', NULL, 1100000, 'Uma vez por amanhecer, permite conjurar porta dimensional. Ao sair e reaparecer, cria fumaça que causa escuridão leve até o fim do próximo turno; vento pode dispersá-la.'),
  ('carrilhao-de-abertura', 'Carrilhão de Abertura', 'Itens maravilhosos', 'raro', NULL, 600000, 'Abre uma fechadura, tranca ou outro objeto abrível a até 36 m, se o som puder alcançá-lo. Tem dez usos e se parte depois do último.'),
  ('chapeu-de-disfarce', 'Chapéu de Disfarce', 'Itens maravilhosos', 'incomum', 'sim', 200000, 'Permite conjurar disfarçar-se à vontade. A magia termina se o chapéu for removido.'),
  ('cimitarra-de-velocidade', 'Cimitarra de Velocidade', 'Armas mágicas', 'muito raro', 'sim', 3500000, 'Concede +2 nas jogadas de ataque e dano e permite atacar com ela como ação bônus a cada turno.'),
  ('cinto-dos-anoes', 'Cinto dos Anões', 'Cintos', 'raro', 'sim', 1500000, 'Aumenta Constituição em 2, até 20, e dá vantagem em Persuasão com anões. Há 50% de chance diária de a barba crescer ou engrossar. Não anões também recebem resistência e vantagem contra veneno, visão no escuro de 18 m e o idioma Anão.'),
  ('cinturao-forca-gigante-colina', 'Cinturão de Força do Gigante da Colina', 'Cinturões', 'raro', 'sim', 2000000, 'Define a Força como 21, se esse valor for maior que o valor atual.'),
  ('cinturao-forca-gigante-pedra-gelo', 'Cinturão de Força do Gigante de Pedra ou do Gelo', 'Cinturões', 'muito raro', 'sim', 5000000, 'Define a Força como 23, se esse valor for maior que o valor atual.'),
  ('cinturao-forca-gigante-fogo', 'Cinturão de Força do Gigante do Fogo', 'Cinturões', 'muito raro', 'sim', 3500000, 'Define a Força como 25, se esse valor for maior que o valor atual.'),
  ('cinturao-forca-gigante-nuvens', 'Cinturão de Força do Gigante das Nuvens', 'Cinturões', 'lendário', 'sim', 20000000, 'Define a Força como 27, se esse valor for maior que o valor atual.'),
  ('cinturao-forca-gigante-tempestade', 'Cinturão de Força do Gigante da Tempestade', 'Cinturões', 'lendário', 'sim', 30000000, 'Define a Força como 29, se esse valor for maior que o valor atual.'),
  ('cola-soberana', 'Cola Soberana', 'Itens maravilhosos', 'lendário', NULL, 1000000, 'Cola dois objetos permanentemente. Cada porção cobre 30 cm² e seca em 1 minuto; a união só é desfeita por solvente universal, óleo de forma etérea ou desejo.'),
  ('colar-de-adaptacao', 'Colar de Adaptação', 'Colares', 'incomum', 'sim', NULL, 'Permite respirar normalmente em qualquer ambiente e dá vantagem contra gases e vapores nocivos.'),
  ('colar-de-bolas-de-fogo', 'Colar de Bolas de Fogo', 'Colares', 'raro', NULL, 800000, 'Possui 1d6 + 3 contas. Cada conta pode ser arremessada e explodir como bola de fogo de 3º nível, CD 15; arremessar contas adicionais aumenta o nível da magia.'),
  ('contas-de-forca', 'Contas de Força', 'Itens maravilhosos', 'raro', NULL, 600000, 'Uma conta arremessada explode, causando 5d4 de dano de energia em uma área de 3 m, com resistência de Destreza CD 15. Depois, forma por 1 minuto uma esfera que pode aprisionar criaturas que falharam na resistência e estavam inteiramente na área.'),
  ('corda-de-escalada', 'Corda de Escalada', 'Cordas', 'incomum', NULL, 300000, 'Corda animada de 18 m que suporta até 1.500 kg e pode mover-se, prender-se, soltar-se, amarrar-se ou enrolar-se por comando. Nós facilitam a escalada; possui CA 20, 20 PV e regenera 1 PV a cada 5 minutos se não for destruída.'),
  ('corda-de-estrangulamento', 'Corda de Estrangulamento', 'Cordas', 'raro', NULL, 1500000, 'Pode tentar impedir uma criatura a até 6 m, que resiste com Destreza CD 15. O alvo pode escapar com Força ou Destreza CD 15; a corda tem CA 20, 20 PV e regenera 1 PV a cada 5 minutos se não for destruída.'),
  ('corrente-de-contas-de-oracao', 'Corrente de Contas de Oração', 'Itens maravilhosos', 'raro', 'clérigo, druida ou paladino', 2000000, 'Possui 1d4 + 2 contas que conjuram magias como ação bônus; os usos são recuperados ao amanhecer. Contas: Abençoar (benção), Curar (curar ferimentos de 2º nível ou restauração menor), Auxiliar (restauração maior), Destruir (marca da punição), Invocar (aliado planar) e Andar no vento (caminhar no vento). Uma conta removida perde a magia.'),
  ('couro-batido-encantador', 'Couro Batido Encantador', 'Armaduras mágicas', 'raro', NULL, 1500000, 'Concede +1 na CA. Como ação bônus, pode assumir a aparência ilusória de roupas comuns ou outro tipo de armadura, mantendo volume e peso.'),
  ('cubo-de-forca', 'Cubo de Força', 'Itens maravilhosos', 'raro', 'sim', 2000000, 'Tem 36 cargas e recupera 1d20 ao amanhecer. Cria por 1 minuto uma barreira cúbica de 4,5 m. Suas faces podem bloquear gases, vento e névoa; matéria inorgânica; matéria orgânica; efeitos de magia; ou tudo. A sexta face desativa a barreira. Certas magias e itens drenam cargas ao tocá-la.'),
  ('cubo-do-portal', 'Cubo do Portal', 'Itens maravilhosos', 'lendário', NULL, 17500000, 'Cada face está ligada a um plano. Pressionar uma vez conjura portal; duas vezes conjura viagem planar (CD 17) para o plano correspondente. Tem 3 cargas e recupera 1d3 ao amanhecer.'),
  ('decantador-de-agua-infinita', 'Decantador de Água Infinita', 'Itens maravilhosos', 'incomum', NULL, 400000, 'Produz água doce ou salgada por comando: Riacho, 4 litros; Fonte, 20 litros; Gêiser, 120 litros em jato de 9 m, que pode causar dano e derrubar uma criatura ou empurrar um objeto.'),
  ('defensora', 'Defensora', 'Armas mágicas', 'lendário', 'sim', 10000000, 'Concede +3 nas jogadas de ataque e dano. No primeiro ataque de cada turno, pode transferir parte ou todo esse bônus para a CA até o início do próximo turno.'),
  ('diadema-da-destruicao', 'Diadema da Destruição', 'Diademas', 'incomum', NULL, 450000, 'Conjura raio ardente com bônus de ataque +5; recupera o uso ao amanhecer.'),
  ('dispositivo-de-kwalish', 'Dispositivo de Kwalish', 'Itens maravilhosos', 'lendário', NULL, 20000000, 'Um barril de ferro que se transforma em veículo semelhante a uma lagosta gigante, para duas criaturas. Tem CA 20, 200 PV, deslocamento e natação de 9 m, é hermético e possui ar para 10 horas dividido entre os ocupantes. Dez alavancas controlam suas funções, incluindo pernas, garras, movimento, direção, luzes e profundidade.'),
  ('elixir-de-saude', 'Elixir de Saúde', 'Poções', 'raro', NULL, 1000000, 'Cura todas as doenças do usuário e remove as condições cego, surdo, paralisado e envenenado.'),
  ('elmo-brilhante', 'Elmo Brilhante', 'Elmos', 'muito raro', 'sim', 5000000, 'Suas gemas podem ser consumidas para conjurar magias, incluindo rajada prismática, muralha de fogo, bola de fogo e luz do dia. Enquanto houver gemas, também pode causar dano radiante a mortos-vivos próximos, conceder resistência a fogo e incendiar uma arma para causar dano adicional. Certas falhas contra magia de fogo podem destruí-lo.'),
  ('elmo-de-compreensao-de-idiomas', 'Elmo de Compreensão de Idiomas', 'Elmos', 'incomum', NULL, 400000, 'Permite conjurar compreender idiomas à vontade.'),
  ('elmo-de-telepatia', 'Elmo de Telepatia', 'Elmos', 'incomum', 'sim', 500000, 'Permite conjurar detectar pensamentos (CD 13) e trocar mensagens telepáticas com a criatura enfocada. Enquanto mantém o foco, também pode conjurar sugestão (CD 13), com uso recuperado ao amanhecer.'),
  ('elmo-de-teletransporte', 'Elmo de Teletransporte', 'Elmos', 'raro', 'sim', 2000000, 'Tem 3 cargas; gasta uma para conjurar teletransporte e recupera 1d3 cargas ao amanhecer.'),
  ('escaravelho-de-protecao', 'Escaravelho de Proteção', 'Itens maravilhosos', 'lendário', 'sim', 25000000, 'Dá vantagem contra magias. Tem 12 cargas; como reação, uma carga pode transformar uma falha contra magia necromântica ou efeito nocivo de morto-vivo em sucesso. Desfaz-se em pó quando gasta a última carga.'),
  ('escudo-mais-1', 'Escudo +1', 'Escudos mágicos', 'incomum', NULL, 500000, 'Concede +1 à CA, além do bônus normal do escudo.'),
  ('escudo-mais-2', 'Escudo +2', 'Escudos mágicos', 'raro', NULL, 2000000, 'Concede +2 à CA, além do bônus normal do escudo.'),
  ('escudo-mais-3', 'Escudo +3', 'Escudos mágicos', 'muito raro', NULL, 5000000, 'Concede +3 à CA, além do bônus normal do escudo.'),
  ('escudo-animado', 'Escudo Animado', 'Escudos mágicos', 'muito raro', 'sim', 2000000, 'Como ação bônus, flutua e protege o usuário como se estivesse empunhado, deixando as mãos livres. Dura 1 minuto ou até ser encerrado, o usuário ficar incapacitado ou morrer.'),
  ('escudo-apanhador-de-flechas', 'Escudo Apanhador de Flechas', 'Escudos mágicos', 'raro', 'sim', 500000, 'Concede +2 na CA contra ataques à distância, além do bônus normal do escudo. Como reação, pode tornar-se alvo de um ataque à distância dirigido a alguém a até 1,5 m.'),
  ('escudo-de-atracao-de-projeteis', 'Escudo de Atração de Projéteis', 'Escudos mágicos', 'raro', 'sim', 2000000, 'Concede resistência ao dano de ataques à distância com armas. Maldição: ataques à distância com arma contra alvos a até 3 m passam a visar o usuário; retirar o escudo não encerra a maldição.'),
  ('escudo-de-protecao-contra-magia', 'Escudo de Proteção contra Magia', 'Escudos mágicos', 'muito raro', 'sim', 2500000, 'Dá vantagem em testes de resistência contra magias e outros efeitos mágicos; ataques com magia têm desvantagem contra o usuário.'),
  ('escudo-sentinela', 'Escudo Sentinela', 'Escudos mágicos', 'incomum', NULL, 400000, 'Concede vantagem em iniciativa e em testes de Sabedoria (Percepção).'),
  ('esfera-de-aniquilacao', 'Esfera de Aniquilação', 'Itens maravilhosos', 'lendário', NULL, 20000000, 'Esfera de 60 cm que oblitera matéria; contato parcial causa 4d10 de dano de energia. Pode ser controlada com Arcanismo CD 25; falhas podem fazê-la avançar sobre o controlador. Contato com portais ou espaços extradimensionais pode destruí-la, transportá-la ou abrir uma brecha planar.'),
  ('espada-dancarina', 'Espada Dançarina', 'Armas mágicas', 'muito raro', 'sim', 5000000, 'Pode ser lançada ao ar com ação bônus para voar até 9 m e atacar usando as estatísticas do usuário. Pode ser comandada a mover-se e atacar novamente; após o quarto ataque, tenta retornar à mão.'),
  ('espada-da-retaliacao', 'Espada da Retaliação', 'Armas mágicas', 'lendário', 'criatura da mesma tendência da espada', 10000000, 'Concede +3 em ataque e dano. Como reação, permite atacar uma criatura ao alcance que tenha causado dano ao usuário; o ataque tem vantagem e ignora imunidade e resistência a dano. Variações: Respondedora, Discutidora, Finalizadora, Gracejo Final, Rebatedora, Replicadora, Retrucadora, Treplicadora e Terminadora, cada uma com tendência e gema próprias.'),
  ('espada-da-vinganca', 'Espada da Vingança', 'Armas mágicas', 'incomum', 'sim', 300000, 'Concede +1 em ataque e dano. Maldição: o usuário reluta em separar-se dela e tem desvantagem ao atacar com outras armas; ao sofrer dano em combate, pode ser compelido a atacar quem o feriu. Removida a maldição, torna-se uma arma +1 comum.'),
  ('espada-decepadora', 'Espada Decepadora', 'Armas mágicas', 'muito raro', 'sim', 2000000, 'Maximiza o dado de dano contra objetos. Um 20 natural contra uma criatura causa 14 de dano cortante adicional; outro 20 em seguida pode decepar parte do corpo. A lâmina também pode emitir luz por palavra de comando.'),
  ('espada-do-furto-de-vidas', 'Espada do Furto de Vidas', 'Armas mágicas', 'raro', 'sim', 2000000, 'Um 20 natural causa 10 de dano necrótico adicional a criaturas que não sejam constructos ou mortos-vivos e concede 10 PV temporários ao usuário.'),
  ('espada-do-sangramento', 'Espada do Sangramento', 'Armas mágicas', 'raro', 'sim', 1800000, 'O dano causado só pode ser recuperado em descansos. Uma vez por turno, pode ferir o alvo; cada ferimento causa 1d4 de dano necrótico no início do turno do alvo até ser tratado ou resistido.'),
  ('espada-vorpal', 'Espada Vorpal', 'Armas mágicas', 'lendário', 'sim', 30000000, 'Concede +3 em ataque e dano e ignora resistência a dano cortante. Um 20 natural pode decepar uma cabeça; certas criaturas sofrem 6d8 de dano cortante adicional em vez disso.'),
  ('espelho-do-aprisionamento', 'Espelho do Aprisionamento', 'Itens maravilhosos', 'muito raro', NULL, 5000000, 'Tem doze celas extradimensionais. Criaturas que veem seu reflexo a até 9 m fazem Carisma CD 15 ou são aprisionadas com seus pertences. Prisioneiros não envelhecem nem precisam comer, beber ou dormir; podem escapar por viagem planar ou ser libertados por comando. Quebrar o espelho liberta todos.'),
  ('estatua-poderes-bodes-de-marfim', 'Estátua de Poderes Incríveis (Bodes de Marfim)', 'Estátuas', 'raro', NULL, 1600000, 'Conjunto de três: o bode de viagem serve como montaria; o bode de trabalho torna-se bode gigante por 3 horas; o bode do terror torna-se bode gigante e fornece uma lança de montaria +1 e uma espada longa +2, além de uma aura de medo.'),
  ('estatua-poderes-cachorro-de-onix', 'Estátua de Poderes Incríveis (Cachorro de Ônix)', 'Estátuas', 'raro', NULL, 1200000, 'Torna-se mastim por até 6 horas; fala Comum, vê no escuro e percebe criaturas e objetos invisíveis. Reutilização após 7 dias.'),
  ('estatua-poderes-corcel-de-obsidiana', 'Estátua de Poderes Incríveis (Corcel de Obsidiana)', 'Estátuas', 'muito raro', NULL, 2000000, 'Torna-se pesadelo por até 24 horas; reutilização após 15 dias. Para usuários de tendência boa, pode ignorar ordens e transportá-los para Hades.'),
  ('estatua-poderes-coruja-de-serpentina', 'Estátua de Poderes Incríveis (Coruja de Serpentina)', 'Estátuas', 'raro', NULL, 500000, 'Torna-se coruja gigante por até 8 horas e comunica-se telepaticamente com o usuário no mesmo plano. Reutilização após 2 dias.'),
  ('estatua-poderes-corvo-de-prata', 'Estátua de Poderes Incríveis (Corvo de Prata)', 'Estátuas', 'incomum', NULL, 300000, 'Torna-se corvo por até 12 horas e pode conjurar mensageiro animal à vontade. Reutilização após 2 dias.'),
  ('estatua-poderes-elefante-de-marmore', 'Estátua de Poderes Incríveis (Elefante de Mármore)', 'Estátuas', 'raro', NULL, 1400000, 'Torna-se elefante por até 24 horas; reutilização após 7 dias.'),
  ('estatua-poderes-grifo-de-bronze', 'Estátua de Poderes Incríveis (Grifo de Bronze)', 'Estátuas', 'raro', NULL, 800000, 'Torna-se grifo por até 6 horas; reutilização após 5 dias.'),
  ('estatua-poderes-leoes-dourados', 'Estátua de Poderes Incríveis (Leões Dourados)', 'Estátuas', 'raro', NULL, 1400000, 'As estátuas são criadas em pares e podem ser usadas juntas ou separadamente. Cada uma torna-se leão por até 1 hora; após o uso, aguarda 7 dias para ser reutilizada.'),
  ('estatua-poderes-mosca-de-ebano', 'Estátua de Poderes Incríveis (Mosca de Ébano)', 'Estátuas', 'raro', NULL, 800000, 'Torna-se mosca gigante por até 12 horas e pode servir de montaria; reutilização após 2 dias.')
) AS items(id, name, subcategory, rarity, attunement, price_cp, description);

COMMIT;
